# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# project = Project.create(name: 'Conquering The World', site: 'zooniverse.org')
# user_1 = User.create(handle: 'conqueror', email: 'hacha@hacha.org', password: '12345678')
# user_2 = User.create(handle: 'remtetle', email: 'remtetle@hacha.org', password: '12345678')
# user_3 = User.create(handle: 'libader', email: 'libader@hacha.org', password: '12345678')
# user_4 = User.create(handle: 'loretti', email: 'loretti@hacha.org', password: '12345678')
# user_5 = User.create(handle: 'jaron', email: 'jaron@hacha.org', password: '12345678')
# user_6 = User.create(handle: 'reberes', email: 'reberes@hacha.org', password: '12345678')
# user_7 = User.create(handle: 'maleor', email: 'maleor@hacha.org', password: '12345678')
# user_8 = User.create(handle: 'rubirestre', email: 'rubirestre@hacha.org', password: '12345678')
# user_9 = User.create(handle: 'anateros', email: 'anateros@hacha.org', password: '12345678')
# user_10 = User.create(handle: 'osimpar', email: 'osimpar@hacha.org', password: '12345678')
# user_1_collaboration_project = Collaboration.create(project: project, user: user_1, points: rand(1..500))
# user_2_collaboration_project = Collaboration.create(project: project, user: user_2, points: rand(1..500))
# user_3_collaboration_project = Collaboration.create(project: project, user: user_3, points: rand(1..500))
# user_4_collaboration_project = Collaboration.create(project: project, user: user_4, points: rand(1..500))
# user_5_collaboration_project = Collaboration.create(project: project, user: user_5, points: rand(1..500))
# user_6_collaboration_project = Collaboration.create(project: project, user: user_6, points: rand(1..500))
# user_7_collaboration_project = Collaboration.create(project: project, user: user_7, points: rand(1..500))
# user_8_collaboration_project = Collaboration.create(project: project, user: user_8, points: rand(1..500))
# user_9_collaboration_project = Collaboration.create(project: project, user: user_9, points: rand(1..500))
# user_10_collaboration_project = Collaboration.create(project: project, user: user_10, points: rand(1..500))

user_1 = User.find_by(handle: 'conqueror')
user_2 = User.find_by(handle: 'remtetle')
user_3 = User.find_by(handle: 'libader')
user_4 = User.find_by(handle: 'loretti')
user_5 = User.find_by(handle: 'jaron')
user_6 = User.find_by(handle: 'reberes')
user_7 = User.find_by(handle: 'maleor')
user_8 = User.find_by(handle: 'rubirestre')
user_9 = User.find_by(handle: 'anateros')
user_10 = User.find_by(handle: 'osimpar')

leaf = Project.find_or_create_by(name: "Leaf Targeting")
user_1_collaboration_leaf = Collaboration.create(project: leaf, user: user_1, points: rand(1..500))
user_2_collaboration_leaf = Collaboration.create(project: leaf, user: user_2, points: rand(1..500))
user_3_collaboration_leaf = Collaboration.create(project: leaf, user: user_3, points: rand(1..500))
user_4_collaboration_leaf = Collaboration.create(project: leaf, user: user_4, points: rand(1..500))
user_5_collaboration_leaf = Collaboration.create(project: leaf, user: user_5, points: rand(1..500))
user_6_collaboration_leaf = Collaboration.create(project: leaf, user: user_6, points: rand(1..500))
user_7_collaboration_leaf = Collaboration.create(project: leaf, user: user_7, points: rand(1..500))
user_8_collaboration_leaf = Collaboration.create(project: leaf, user: user_8, points: rand(1..500))
user_9_collaboration_leaf = Collaboration.create(project: leaf, user: user_9, points: rand(1..500))
user_10_collaboration_leaf = Collaboration.create(project: leaf, user: user_10, points: rand(1..500))